### ISSUE TITLE
Can't Import

### ISSUE THREAD

**Issue by bobbyg603** [BugSplat-Git/bugsplat-py#9]
1. Ran:

```sh
pip install bugsplat==1.0.1
```

2. Wrote the following script:

main.py
```py
from bugsplat import BugSplat
from helpers import crash

bugsplat = BugSplat("fred", "my-python-crasher", "1.0")

bugsplat.set_default_app_key('key!')
bugsplat.set_default_description('description!')
bugsplat.set_default_email('fred@bugsplat.com')
bugsplat.set_default_user('Fred')

try:
    crash()
except Exception as e:
    bugsplat.post(
        e,
        additional_file_paths=[],
        app_key='other key!',
        description='other description!',
        email='barney@bugsplat.com',
        user='Barney'
    )
```

helpers.py
```sh

def crash():
    _sampleStackFrame0(1337)

def _sampleStackFrame0(n):
    m = n + 9001
    _sampleStackFrame1(m)

def _sampleStackFrame1(n):
    _sampleStackFrame2(n)

def _sampleStackFrame2(n):
    x = 1 / 0
```

3. Got the following error:
```sh
(venv) bobby@Mr-Presidents-MacBook-Pro my-python-crasher % python main.py
Traceback (most recent call last):
  File "/Users/bobby/Desktop/bugsplat/my-python-crasher/main.py", line 1, in <module>
    from bugsplat import BugSplat
  File "/Users/bobby/Desktop/bugsplat/my-python-crasher/venv/lib/python3.10/site-packages/bugsplat/__init__.py", line 11, in <module>
    from .bugsplat import BugSplat
  File "/Users/bobby/Desktop/bugsplat/my-python-crasher/venv/lib/python3.10/site-packages/bugsplat/bugsplat.py", line 11, in <module>
    logging.basicConfig(level="info")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 2059, in basicConfig
    root.setLevel(level)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1452, in setLevel
    self.level = _checkLevel(level)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 198, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'info'
```

**Comment by bobbyg603** [comment]
Fixed in 1.0.2
